### ISSUE TITLE
Rust nightly stabilized asm! and global_asm! requires package specifiers

### ISSUE THREAD

**Issue by dancrossnyc** [gz/rust-x86#117]
Rust 1.59 is stabilizing `asm!()` and `global_asm!()`, but now requires explicit `use` statements (or package qualification) when using these macros. This causes building `x86` to fail on the latest nightly.

The fix is easy: adding `use core::arch:asm;` statements to src/{task,irq,tlb,lib,debugregs}.rs. I will send a PR.

**Comment by mkroening** [comment]
It would be awesome to have a release containing the fix. :)

**Comment by gz** [comment]
Sure, I released 0.44 just now.
