### ISSUE TITLE
`llvm_asm!` is deprecated and removed on latest nightly

### ISSUE THREAD

**Issue by not-matthias** [gz/rust-x86#120]
It should be replaced with the newer `asm!` macro.

See: https://github.com/rust-lang/rust/issues/70173

**Comment by dancrossnyc** [comment]
https://github.com/gz/rust-x86/pull/121 addresses this.

**Comment by dancrossnyc** [comment]
PR #121 is now committed, and @gz cut a new crate release, so this should be good to go now!

**Comment by gz** [comment]
@dancrossnyc pull request is now merged. Thanks for reporting!
