### ISSUE TITLE
Combine with https://github.com/Tobba/libcpu

### ISSUE THREAD

**Issue by Ericson2314** [gz/rust-x86#15]
There seems to be good overlap with between this and that. This is more complete, but I find the lack of 32-bit vs 64-bit `#![cfg(..)]`s confusing (or is only 64-bit meant to be supported?).

CC @Tobba

**Comment by gz** [comment]
Ideally, this crate would contain everything that is mentioned in the Intel SDM, including the 32-bit differences. Right now, I did not bother supporting 32-bit. I mostly consider 32bits deprecated for the x86 world, but I don't think there are as many changes if we want to provide both. One thing to consider is that the crate would ideally be able provide access to both, 32-bit and 64-bit data structure descriptions on a 64bit or 32bit host system. Therefore, I'm not yet sure if the cfg() approach would be the best option, but I'm open to suggestions.

**Comment by Ericson2314** [comment]
Yeah maybe namespace types for both a architectures that are always there, and put assembly snippets and alias native types in a `native` module.

**Comment by Ericson2314** [comment]
Looks like libcpu also has a few more convenient but flags for IDT entries it would be nice to have.

**Comment by steveklabnik** [comment]
I am vaguely interested in 32-bit stuff so that I could write my protected -> long mode code in Rust. But since I have a working asm implementation, it's not that big a deal.

**Comment by Ericson2314** [comment]
WIP: https://github.com/gz/rust-x86/pull/16
