### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by InfiniteCoder01** [gz/rust-x86#158]
Is the project abandoned?
Seems like interrupt API is not finished and there were no commits since Nov 25, 2023

**Comment by gz** [comment]
It's not abandoned. But at least I am not actively adding things right now. Happy to accept your PRs if you want to work on interrupts. What API do you think is incomplete? This crate is used in multiple OS kernels.

Check https://github.com/vmware-labs/node-replicated-kernel for an example on how to program interrupts with x86.
