### ISSUE TITLE
Segmentation fault.

### ISSUE THREAD

**Issue by c-edw** [gz/rust-x86#40]
The following code is causing a segmentation fault.

```rust
unsafe { wrmsr(0x150, 0x80000011ecc00000); }
```

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.47 secs
     Running `target/debug/x86test`
Segmentation fault (core dumped)
```

**Comment by gz** [comment]
Hi, Can you explain in more detail what exactly you're trying to do? What is x86test and at what privilege level does it run?

**Comment by c-edw** [comment]
@gz `x86test` is just a project for testing out this crate, it runs in userspace like you said. I'm looking to be able to write to MSR registers. Something like the `wrmsr` utility from `msr-tools`, but I want to do it programatically rather than call the binary. Thanks for letting me know that it won't work in this way.

**Comment by deepsthewarrior** [comment]
Please refer to this. 
https://stackoverflow.com/questions/26331730/root-has-segfault-executing-rdmsr-assembly-code
