### ISSUE TITLE
Publish 0.9.0 crate 

### ISSUE THREAD

**Issue by robert-w-gries** [gz/rust-x86#41]
Hi Gerd, I see that you're refactoring the crate. I look forward to upgrading my project to use the new API.

Since the new API is not stabilized yet, I haven't been able to use latest `master` code in my project without breakages.  I decided to fork `rust-x86` and point my project to a branch that doesn't include the refactored API.

Can you publish a crate version `0.9.0` that includes all work before April 20, 2017?  It would be nice to use an official crate version and upgrade to the new API when it is stabilized.

**Comment by gz** [comment]
Hi Robert
Sure, would that commit work for you becoming 0.9?
https://github.com/gz/rust-x86/commit/1e2efb6b7a0d76d9b672e09862515f5ac2541d9f

**Comment by robert-w-gries** [comment]
Yep, that'd be perfect! Thank you

**Comment by gz** [comment]
I released a 0.9 crate version (see the 0.9 branch)
