### ISSUE TITLE
tsc_frequency fails with a panic, due to a division by zero

### ISSUE THREAD

**Issue by stlankes** [gz/rust-x86#65]
Issue hermitcore/libhermit-rs#30 is an example that the denominator of TscInfo isn't alway correctly determined. On some platforms are the denominator 0. In this case, `get_tsc_info` should return None.

**Comment by gz** [comment]
Hi, it seems this issue is related to the raw-cpuid crate https://github.com/gz/rust-cpuid? Do you mind reporting it there?

**Comment by stlankes** [comment]
Yes, you are right. I will report there.

**Comment by gz** [comment]
@stlankes x86 0.33.0 contains raw-cpuid 8.0.0 with the new API.

**Comment by stlankes** [comment]
Great! Thanks for the quick integration.
