### ISSUE TITLE
Rust ask to change asm to llvm_asm

### ISSUE THREAD

**Issue by javierdallamore** [gz/rust-x86#67]
Hi,

using

cargo 1.45.0-nightly (9fcb8c1d2 2020-05-25)

I get 63 of these errors:

```
error: legacy asm! syntax is no longer supported
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/x86-0.19.0/src/lib.rs:83:5
   |
83 |     asm!("hlt" :::: "volatile");
   |     ----^^^^^^^^^^^^^^^^^^^^^^^^
   |     |
   |     help: replace with: `llvm_asm!`
```

As the error says, changing asm to llvm_asm works.

**Comment by gz** [comment]
Hi, I believe you are using an older version of x86. The latest version has been converted to llvm_asm. Does that work for you?

**Comment by javierdallamore** [comment]
I was building this project: https://github.com/twitter/rezolus

I will check their dependencies, tks.
