### ISSUE TITLE
More documentation on modules that require MMIO regions

### ISSUE THREAD

**Issue by ethindp** [gz/rust-x86#68]
So I'm really confused on some of the functions that this crate has. For example the `apic::xapic::XAPIC::new()` function takes an array of [u32]. However, the comment only says:
```rust
    /// Create a new xAPIC object for the local CPU.
    ///
    /// Pass the xAPCI region which is at XXX unless you have
    /// relocated the region.
```
However, this is really confusing. Do I pass in every single XAPIC address (the full address)? Do I pass in the base? Do I only pass in offsets? This definitely requires some clarification.

**Comment by gz** [comment]
Hi,

Thanks for bringing this up, does this code-example clarify how to use it? If so I can update the documentation.

```
/// Return the base address of the xAPIC (x86 Interrupt controller)
fn find_apic_base() -> u64 {
    use x86::msr::{rdmsr, IA32_APIC_BASE};
    unsafe {
        let base = rdmsr(IA32_APIC_BASE);
        base & !0xfff
    }
}

fn init_apic() -> xapic::XAPICDriver {
    let base = find_apic_base();
    let regs: &'static mut [u32] = unsafe { core::slice::from_raw_parts_mut(base as *mut _, 256) };
    XAPIC::new(regs);
}
```

**Comment by ethindp** [comment]
That does help quite a bit. I think the parameters just need to be elaborated on.
